services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql:data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data: